/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatAmIPayingRouteImport } from './routes/what-am-i-paying'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrustSchemeIdRouteImport } from './routes/trust.$schemeId'
import { Route as SchemesSchemeIdRouteImport } from './routes/schemes.$schemeId'
import { Route as SchemesSchemeIdManagerRouteImport } from './routes/schemes.$schemeId.manager'

const WhatAmIPayingRoute = WhatAmIPayingRouteImport.update({
  id: '/what-am-i-paying',
  path: '/what-am-i-paying',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSchemeIdRoute = TrustSchemeIdRouteImport.update({
  id: '/trust/$schemeId',
  path: '/trust/$schemeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesSchemeIdRoute = SchemesSchemeIdRouteImport.update({
  id: '/schemes/$schemeId',
  path: '/schemes/$schemeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesSchemeIdManagerRoute = SchemesSchemeIdManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => SchemesSchemeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/what-am-i-paying': typeof WhatAmIPayingRoute
  '/schemes/$schemeId': typeof SchemesSchemeIdRouteWithChildren
  '/trust/$schemeId': typeof TrustSchemeIdRoute
  '/schemes/$schemeId/manager': typeof SchemesSchemeIdManagerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/what-am-i-paying': typeof WhatAmIPayingRoute
  '/schemes/$schemeId': typeof SchemesSchemeIdRouteWithChildren
  '/trust/$schemeId': typeof TrustSchemeIdRoute
  '/schemes/$schemeId/manager': typeof SchemesSchemeIdManagerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/what-am-i-paying': typeof WhatAmIPayingRoute
  '/schemes/$schemeId': typeof SchemesSchemeIdRouteWithChildren
  '/trust/$schemeId': typeof TrustSchemeIdRoute
  '/schemes/$schemeId/manager': typeof SchemesSchemeIdManagerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/what-am-i-paying'
    | '/schemes/$schemeId'
    | '/trust/$schemeId'
    | '/schemes/$schemeId/manager'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/what-am-i-paying'
    | '/schemes/$schemeId'
    | '/trust/$schemeId'
    | '/schemes/$schemeId/manager'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/what-am-i-paying'
    | '/schemes/$schemeId'
    | '/trust/$schemeId'
    | '/schemes/$schemeId/manager'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  WhatAmIPayingRoute: typeof WhatAmIPayingRoute
  SchemesSchemeIdRoute: typeof SchemesSchemeIdRouteWithChildren
  TrustSchemeIdRoute: typeof TrustSchemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-am-i-paying': {
      id: '/what-am-i-paying'
      path: '/what-am-i-paying'
      fullPath: '/what-am-i-paying'
      preLoaderRoute: typeof WhatAmIPayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/$schemeId': {
      id: '/trust/$schemeId'
      path: '/trust/$schemeId'
      fullPath: '/trust/$schemeId'
      preLoaderRoute: typeof TrustSchemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$schemeId': {
      id: '/schemes/$schemeId'
      path: '/schemes/$schemeId'
      fullPath: '/schemes/$schemeId'
      preLoaderRoute: typeof SchemesSchemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$schemeId/manager': {
      id: '/schemes/$schemeId/manager'
      path: '/manager'
      fullPath: '/schemes/$schemeId/manager'
      preLoaderRoute: typeof SchemesSchemeIdManagerRouteImport
      parentRoute: typeof SchemesSchemeIdRoute
    }
  }
}

interface SchemesSchemeIdRouteChildren {
  SchemesSchemeIdManagerRoute: typeof SchemesSchemeIdManagerRoute
}

const SchemesSchemeIdRouteChildren: SchemesSchemeIdRouteChildren = {
  SchemesSchemeIdManagerRoute: SchemesSchemeIdManagerRoute,
}

const SchemesSchemeIdRouteWithChildren = SchemesSchemeIdRoute._addFileChildren(
  SchemesSchemeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  WhatAmIPayingRoute: WhatAmIPayingRoute,
  SchemesSchemeIdRoute: SchemesSchemeIdRouteWithChildren,
  TrustSchemeIdRoute: TrustSchemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
